### ISSUE TITLE
clicking the settings button > Map Settings crashes the Sunshine app

### ISSUE THREAD

**Issue by andrericardo** [udacity/Sunshine-Version-2#2]
To reproduce simply checkout 6.10_update_map_intent and run with emulator Nexus_5_API_21
```
02-15 15:03:04.864    2358-2358/com.example.android.sunshine.app D/AndroidRuntime﹕ Shutting down VM
    --------- beginning of crash
02-15 15:03:04.866    2358-2358/com.example.android.sunshine.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.example.android.sunshine.app, PID: 2358
    android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
            at android.database.AbstractCursor.checkPosition(AbstractCursor.java:426)
            at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
            at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:50)
            at android.database.CursorWrapper.getString(CursorWrapper.java:114)
            at com.example.android.sunshine.app.ForecastFragment.openPreferredLocationInMap(ForecastFragment.java:202)
            at com.example.android.sunshine.app.ForecastFragment.onOptionsItemSelected(ForecastFragment.java:123)
            at android.support.v4.app.Fragment.performOptionsItemSelected(Fragment.java:1894)
            at android.support.v4.app.FragmentManagerImpl.dispatchOptionsItemSelected(FragmentManager.java:2034)
            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:356)
            at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:155)
            at android.support.v7.app.ActionBarActivityDelegate$1.onMenuItemSelected(ActionBarActivityDelegate.java:74)
            at android.support.v7.app.ActionBarActivityDelegateBase.onMenuItemSelected(ActionBarActivityDelegateBase.java:556)
            at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:802)
            at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:949)
            at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:939)
            at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:187)
            at android.widget.AdapterView.performItemClick(AdapterView.java:300)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1143)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3044)
            at android.widget.AbsListView$3.run(AbsListView.java:3833)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by benslamajihed** [comment]
in my opinion is not binding but rather to CursorIndexOutOfBoundsException ( size of array or index )
i think "out of bounds" =>  you call  index  doen't exist  verify Adapter of  list
