### ISSUE TITLE
Can not launch Sunshine app on Mac OS X

### ISSUE THREAD

**Issue by vchepeli** [udacity/Sunshine-Version-2#89]
Uploading file
    local path: /Users/vchepeli/Documents/AndroidStudioProjects/Sunshine-Version-2/app/build/outputs/apk/app-debug.apk
    remote path: /data/local/tmp/com.example.android.sunshine.app
Installing com.example.android.sunshine.app
DEVICE SHELL COMMAND: pm install -r "/data/local/tmp/com.example.android.sunshine.app"
    pkg: /data/local/tmp/com.example.android.sunshine.app
Success

Launching application: com.example.android.sunshine.app/com.example.android.sunshine.app.MainActivity.
DEVICE SHELL COMMAND: am start  -n "com.example.android.sunshine.app/com.example.android.sunshine.app.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -Xlint:deprecation
Error: Unknown option: -X
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Intent.getType()' on a null object reference
    at com.android.commands.am.Am.runStart(Am.java:701)
    at com.android.commands.am.Am.onRun(Am.java:305)
    at com.android.internal.os.BaseCommand.run(BaseCommand.java:47)
    at com.android.commands.am.Am.main(Am.java:97)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:249)

**Comment by vchepeli** [comment]
Thats my fault. Issue can be closed
